### ISSUE TITLE
Typescript constructor access modifiers are not working in dev mode

### ISSUE THREAD

**Issue by ratoi-crysty** [preactjs-templates/typescript#34]
When creating a class in typescript with access modifiers in constructor, the constructor parameters are not converted into class properties. The following example will not work correctly
`export class Test {
    constructor(public foo: string) {}
}
console.log(new Test("bar"));`  

Steps to reproduce:
- create a new project using the cli command: `preact create typescript projectName`
- create the class with access modifiers in constructor
- run the project in dev mode using: `npm run dev`

Note: this issue is not reproducible using the build command, it is only reproducible in dev (prect watch) mode.

**Comment by RyanChristian4427** [comment]
It looks to be an issue with the version of Typescript that the CLI is using. I'll try to get a fix submitted as PR soon here.

**Comment by RyanChristian4427** [comment]
Do you mind trying to add the CLI as a dependency to your application from the CLI's source? Seems like this bug has been fixed between rc-14 and the current state.

**Comment by ratoi-crysty** [comment]
It has it from the beginning. The version in package.json is: "^3.0.0-next.19" but the istalled one is "3.0.0-rc.14". 
Furthermore, I've repeated the test after updating the global CLI to `3.0.0-rc.14` and creating a new project. And is still reproducible.

**Comment by RyanChristian4427** [comment]
`next.19` I think resolves to `rc.14`. 

What I'm asking is if you can attempt to run from the CLI source.

> Furthermore, I've repeated the test after updating the global CLI to 3.0.0-rc.14 and creating a new project. And is still reproducible.

The global CLI has nothing to do with running a local project. The global CLI only helps scaffold a new project. That's all it does.

**Comment by ratoi-crysty** [comment]
Tested using a local linked version of the CLI, and indeed it works. Thanks for your support.

**Comment by RyanChristian4427** [comment]
Glad to hear it. Sorry, I know that's not a brilliant solution, but it'll be an option until the next CLI release. Alternatively you can try an older CLI version, but no idea if that'll work.
